server:
  port: 8084

bot:
  name: "UGA_Helper_bot"
  token: "6683608461:AAH9oZyl2pYRozPZsfEQ7WPBZmhOzO_Cg8M"

spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: user
    password: 2903
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message
